name: kd_translater
description: "AI Powered translater"
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.4.0
  http: ^1.4.0
  speech_to_text: ^7.0.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: assets/app_logo.png
  android: true
  ios: true

